# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "Phosphorus's Blog"
subtitle: ''
description: ''
keywords:
author: Phosphorus
language: es
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://phosphorus-moscu.gitlab.io/
root: ""
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: phosphorus

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

all_minifier: true

asset_pipeline:
  revisioning:
    enable: true
    keep: false
    selectors:
      'img[data-orign]':  data-orign
      'img[data-src]': 'data-src'
      'img[src]': 'src'
      'link[rel="apple-touch-icon"]': 'href'
      'link[rel="icon"]': 'href'
      'link[rel="shortcut icon"]': 'href'
      'link[rel="stylesheet"]': 'href'
      'script[src]': 'src'
      'source[src]': 'src'
      'video[poster]': 'poster'
      'video[src]': 'src'
  clean_css:
    enable: false
  uglify_js:
    enable: true
  imagemin:
    enable: true
    interlaced: false
    multipass: true
    optimizationLevel: 3
    pngquant: true
    progressive: true
  html_minifier:
    enable: true
    ignore_error: false
    removeComments: true
    removeCommentsFromCDATA: true
    collapseWhitespace: true
    collapseBooleanAttributes: true
    removeEmptyAttributes: true
    minifyJS: true
    minifyCSS: false

revisioning:
  enable: true
  keep: false
  selectors:
    'img[data-orign]':  data-orign
    'img[data-src]': 'data-src'
    'img[src]': 'src'
    'link[rel="apple-touch-icon"]': 'href'
    'link[rel="icon"]': 'href'
    'link[rel="shortcut icon"]': 'href'
    'link[rel="stylesheet"]': 'href'
    'script[src]': 'src'
    'source[src]': 'src'
    'video[poster]': 'poster'
    'video[src]': 'src'

imagemin:
  enable: true
  interlaced: false
  multipass: true
  optimizationLevel: 3
  pngquant: true
  progressive: true



uglify_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'

clean_css:
  enable: false
  exclude: 
    - '*.min.css'



lazyload:
  enable: true
  imgContainer: true
  post:
     only: true
     excludeEncrypt: true
  loadingImg: # eg /images/loading.gif


pwa:
  manifest:
    path: manifest.json
    body:
      name: "Phosphorus's Blog"
      short_name: "Blog"
      description: "A readable Hacker News app"
      lang: es-ES
      display: standalone
      background_color: "#ecedee"
      theme_color: "#414852"
      start_url: "./index.html"
      scope: "."
      orientation: "any"
      icons:
        - src: icons/favicon-32x32.png
          sizes: 32x32
          type: image/png
        - src: icons/icon-192x192.png
          sizes: 192x192
          type: image/png
        - src: icons/icon-512x512.png
          sizes: 512x512
          type: image/png
  # Generate sw.js
  serviceWorker:
    enable: true
    sw: sw.js

minify:
  enable: true
  html:
    enable: true
  css:
    enable: false
    exclude:
      - '*.min.css'
  js:
    enable: true
    exclude:
      - '*.min.js'
  svg:
    enable: true
    include:
      - '*.svg'
      - '!*.min.svg'
  gzip:
    enable: true
    include:
      - '*.html'
      - '*.css'
      - '*.js'
      - '*.txt'
      - '*.ttf'
      - '*.atom'
      - '*.stl'
      - '*.xml'
      - '*.svg'
      - '*.eot'
      - '*.json'
  brotli:
    enable: true
    include:
      - '*.html'
      - '*.css'
      - '*.js'
      - '*.txt'
      - '*.ttf'
      - '*.atom'
      - '*.stl'
      - '*.xml'
      - '*.svg'
      - '*.eot'
      - '*.json'
  xml:
    enable: true
    include:
      - '*.xml'
      - '!*.min.xml'
  json:
    enable: false
    include:
      - '*.json'
      - '!*.min.json'
